version: '2.0'
services:
  web:
    image: coral/coral_frontend:3.0.0
    ports: 
      - '80:80'
    depends_on:
      - api
    volumes:
      - './clientConfig.json:/usr/share/nginx/html/clientConfig.json'
  api:
    image: coral/coral_backend:3.0.0
    ports:
      - '9000:80'
