version: 2.1

executors:
  node-executor:
    working_directory: ~/phovea
    docker:
      - image: circleci/python:3.7.11-buster-node-browsers # for node version see Dockerfile on https://hub.docker.com/r/circleci/python

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  slack: circleci/slack@3.4.2

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/ecr-login
      - run:
          name: Show Node.js and npm version
          command: |
            node -v
            npm -v
      - run:
          name: Show Python and pip version
          command: |
            python --version
            pip --version
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}      
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths: ./node_modules          
      - deploy:
          name: Build and deploy
          command: |
            case "${CIRCLE_BRANCH}${CIRCLE_TAG}" in
            master)
              awsTag="latest"
              ;;
            *)
              awsTag="${CIRCLE_BRANCH//\//_}${CIRCLE_TAG}" # replace `/` with `_` in branch name
              ;;
            esac
            echo "using tag: --${awsTag}--"
            node build.js --injectVersion --skipSaveImage --useSSH --skipTests --noDefaultTags --pushExtra=${awsTag} --pushTo=478950388974.dkr.ecr.eu-central-1.amazonaws.com/caleydo
      - store_artifacts:
          path: build
          destination: build
      - deploy:
          name: Cleanup untagged AWS repositories
          command: |
            baseName=${CIRCLE_PROJECT_REPONAME%_product}
            # list repos filter to just the one of this product and delete untagged ones
            aws ecr describe-repositories --output text | cut -f6 | grep "caleydo/${baseName}" | while read line; do aws ecr list-images --repository-name $line --filter tagStatus=UNTAGGED --query 'imageIds[*]' --output text | while read imageId; do aws ecr batch-delete-image --output text --repository-name $line --image-ids imageDigest=$imageId; done; done
      - deploy:
          name: Restart AWS task # assumes the task definition is called <reponame>-<branch>
          command: |
            # cleanup name by removing the _product suffix
            baseName=${CIRCLE_PROJECT_REPONAME%_product}
            awsFamily="${baseName}-${CIRCLE_BRANCH//\//_}" # replace `/` with `_` in branch name
            echo "awsFamily --${awsFamily}--"
            tasksExists=$(aws --output text ecs list-task-definitions --family-prefix ${awsFamily})
            echo "existsTaskDefinition? --${tasksExists}--"
            if [ ! -z "$tasksExists" ]; then
              isTaskRunning=$(aws --output text ecs list-tasks --cluster JKU_ASG_Cluster --family ${awsFamily})
              echo "isTaskRunning? --${isTaskRunning}--"
              if [ ! -z "$isTaskRunning" ]; then
                taskId=$(echo "${isTaskRunning}" | cut -f2)
                echo "taskId--${taskId}--"
                aws --output text ecs stop-task --cluster JKU_ASG_Cluster --task ${taskId}
              fi
              aws --output text ecs run-task --cluster JKU_ASG_Cluster --task-definition ${awsFamily} --started-by CircleCIAutoUpdate
            fi
      - slack/status:
          success_message: ':tada: Running _$CIRCLE_JOB job_ for _$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH branch_ has succeeded!'
          failure_message: ':skull_and_crossbones: Running _$CIRCLE_JOB job_ for _$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH branch_ has failed!'
workflows:
  version: 2.1
  build-nightly:
    triggers:
      - schedule:
          cron: "45 0 * * 1-5" # "At 00:45 on every day-of-week from Monday through Friday.”, see: https://crontab.guru/#45_0_*_*_1-5
          filters:
            branches:
              only:
                - develop
    jobs:
      - build
  build-branch:
    jobs:
      - build:
          context:
              - org-global
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          context:
              - org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
orbs: